/*
 * Generated by asn1c
 * From ASN.1 module "Ieee1609Dot2Dot1Acpc"
 * 	found in "Ieee1609Dot2Dot1Acpc.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -fprefix=Vanetza_Security_ -R`
 */

#ifndef	_Vanetza_Security_AprvHashCalculationInput_H_
#define	_Vanetza_Security_AprvHashCalculationInput_H_


#include "asn_application.h"

/* Including external dependencies */
#include "Uint8.h"
#include "AcpcTreeId.h"
#include "IValue.h"
#include "BIT_STRING.h"
#include "OCTET_STRING.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Vanetza_Security_AprvHashCalculationInput */
typedef struct Vanetza_Security_AprvHashCalculationInput {
	Vanetza_Security_Uint8_t	 version;
	Vanetza_Security_AcpcTreeId_t	 acpcTreeId;
	Vanetza_Security_IValue_t	 acpcPeriod;
	BIT_STRING_t	 childNodeId;
	OCTET_STRING_t	 parentNodeValue;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Vanetza_Security_AprvHashCalculationInput_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Vanetza_Security_AprvHashCalculationInput;

#ifdef __cplusplus
}
#endif

#endif	/* _Vanetza_Security_AprvHashCalculationInput_H_ */
#include "asn_internal.h"
