/*
 * Generated by asn1c
 * From ASN.1 module "Ieee1609Dot2Dot1CamRaInterface"
 * 	found in "Ieee1609Dot2Dot1CamRaInterface.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -fprefix=Vanetza_Security_ -R`
 */

#ifndef	_Vanetza_Security_CamRaInterfacePdu_H_
#define	_Vanetza_Security_CamRaInterfacePdu_H_


#include "asn_application.h"

/* Including external dependencies */
#include "RaCamBatchRequest.h"
#include "CamRaBatchResponse.h"
#include "constr_CHOICE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Vanetza_Security_CamRaInterfacePdu_PR {
	Vanetza_Security_CamRaInterfacePdu_PR_NOTHING,	/* No components present */
	Vanetza_Security_CamRaInterfacePdu_PR_raCamBatchRequest,
	Vanetza_Security_CamRaInterfacePdu_PR_camRaBatchResponse
	/* Extensions may appear below */
	
} Vanetza_Security_CamRaInterfacePdu_PR;

/* Vanetza_Security_CamRaInterfacePdu */
typedef struct Vanetza_Security_CamRaInterfacePdu {
	Vanetza_Security_CamRaInterfacePdu_PR present;
	union Vanetza_Security_CamRaInterfacePdu_u {
		Vanetza_Security_RaCamBatchRequest_t	 raCamBatchRequest;
		Vanetza_Security_CamRaBatchResponse_t	 camRaBatchResponse;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Vanetza_Security_CamRaInterfacePdu_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Vanetza_Security_CamRaInterfacePdu;

#ifdef __cplusplus
}
#endif

#endif	/* _Vanetza_Security_CamRaInterfacePdu_H_ */
#include "asn_internal.h"
