/*
 * Generated by asn1c
 * From ASN.1 module "Ieee1609Dot2CrlBaseTypes"
 * 	found in "Ieee1609Dot2CrlBaseTypes.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -fprefix=Vanetza_Security_ -R`
 */

#ifndef	_Vanetza_Security_CrlContents_H_
#define	_Vanetza_Security_CrlContents_H_


#include "asn_application.h"

/* Including external dependencies */
#include "Uint8.h"
#include "CrlSeries.h"
#include "HashedId8.h"
#include "Time32.h"
#include "CrlPriorityInfo.h"
#include "TypeSpecificCrlContents.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Vanetza_Security_CrlContents */
typedef struct Vanetza_Security_CrlContents {
	Vanetza_Security_Uint8_t	 version;
	Vanetza_Security_CrlSeries_t	 crlSeries;
	Vanetza_Security_HashedId8_t	 crlCraca;
	Vanetza_Security_Time32_t	 issueDate;
	Vanetza_Security_Time32_t	 nextCrl;
	Vanetza_Security_CrlPriorityInfo_t	 priorityInfo;
	Vanetza_Security_TypeSpecificCrlContents_t	 typeSpecific;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Vanetza_Security_CrlContents_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Vanetza_Security_CrlContents;

#ifdef __cplusplus
}
#endif

#endif	/* _Vanetza_Security_CrlContents_H_ */
#include "asn_internal.h"
