/*
 * Generated by asn1c
 * From ASN.1 module "Ieee1609Dot2Dot1EcaEeInterface"
 * 	found in "Ieee1609Dot2Dot1EcaEeInterface.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -fprefix=Vanetza_Security_ -R`
 */

#ifndef	_Vanetza_Security_EeEcaCertRequest_H_
#define	_Vanetza_Security_EeEcaCertRequest_H_


#include "asn_application.h"

/* Including external dependencies */
#include "Uint8.h"
#include "Time32.h"
#include "CertificateType.h"
#include "ToBeSignedCertificate.h"
#include "IA5String.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Vanetza_Security_EeEcaCertRequest */
typedef struct Vanetza_Security_EeEcaCertRequest {
	Vanetza_Security_Uint8_t	 version;
	Vanetza_Security_Time32_t	 generationTime;
	Vanetza_Security_CertificateType_t	 type;
	Vanetza_Security_ToBeSignedCertificate_t	 tbsCert;
	IA5String_t	*canonicalId;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Vanetza_Security_EeEcaCertRequest_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Vanetza_Security_EeEcaCertRequest;
extern asn_SEQUENCE_specifics_t asn_SPC_Vanetza_Security_EeEcaCertRequest_specs_1;
extern asn_TYPE_member_t asn_MBR_Vanetza_Security_EeEcaCertRequest_1[5];

#ifdef __cplusplus
}
#endif

#endif	/* _Vanetza_Security_EeEcaCertRequest_H_ */
#include "asn_internal.h"
