/*
 * Generated by asn1c
 * From ASN.1 module "Ieee1609Dot2CrlBaseTypes"
 * 	found in "Ieee1609Dot2CrlBaseTypes.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -fprefix=Vanetza_Security_ -R`
 */

#ifndef	_Vanetza_Security_ExpansionAlgorithmIdentifier_H_
#define	_Vanetza_Security_ExpansionAlgorithmIdentifier_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeEnumerated.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Vanetza_Security_ExpansionAlgorithmIdentifier {
	Vanetza_Security_ExpansionAlgorithmIdentifier_sha256ForI_aesForJ	= 0,
	Vanetza_Security_ExpansionAlgorithmIdentifier_sm3ForI_sm4ForJ	= 1
	/*
	 * Enumeration is extensible
	 */
} e_Vanetza_Security_ExpansionAlgorithmIdentifier;

/* Vanetza_Security_ExpansionAlgorithmIdentifier */
typedef long	 Vanetza_Security_ExpansionAlgorithmIdentifier_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Vanetza_Security_ExpansionAlgorithmIdentifier;
asn_struct_free_f Vanetza_Security_ExpansionAlgorithmIdentifier_free;
asn_struct_print_f Vanetza_Security_ExpansionAlgorithmIdentifier_print;
asn_constr_check_f Vanetza_Security_ExpansionAlgorithmIdentifier_constraint;
ber_type_decoder_f Vanetza_Security_ExpansionAlgorithmIdentifier_decode_ber;
der_type_encoder_f Vanetza_Security_ExpansionAlgorithmIdentifier_encode_der;
xer_type_decoder_f Vanetza_Security_ExpansionAlgorithmIdentifier_decode_xer;
xer_type_encoder_f Vanetza_Security_ExpansionAlgorithmIdentifier_encode_xer;
jer_type_encoder_f Vanetza_Security_ExpansionAlgorithmIdentifier_encode_jer;
oer_type_decoder_f Vanetza_Security_ExpansionAlgorithmIdentifier_decode_oer;
oer_type_encoder_f Vanetza_Security_ExpansionAlgorithmIdentifier_encode_oer;
per_type_decoder_f Vanetza_Security_ExpansionAlgorithmIdentifier_decode_uper;
per_type_encoder_f Vanetza_Security_ExpansionAlgorithmIdentifier_encode_uper;
per_type_decoder_f Vanetza_Security_ExpansionAlgorithmIdentifier_decode_aper;
per_type_encoder_f Vanetza_Security_ExpansionAlgorithmIdentifier_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _Vanetza_Security_ExpansionAlgorithmIdentifier_H_ */
#include "asn_internal.h"
