/*
 * Generated by asn1c
 * From ASN.1 module "Ieee1609Dot2Dot1CertManagement"
 * 	found in "Ieee1609Dot2Dot1CertManagement.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -fprefix=Vanetza_Security_ -R`
 */

#ifndef	_Vanetza_Security_MultiSignedCtl_H_
#define	_Vanetza_Security_MultiSignedCtl_H_


#include "asn_application.h"

/* Including external dependencies */
#include "Ieee1609dot2dot1MsctlType.h"
#include "ANY.h"
#include "asn_ioc.h"
#include "FullIeeeTbsCtl.h"
#include "SequenceOfCertificate.h"
#include "OPEN_TYPE.h"
#include "constr_CHOICE.h"
#include "asn_SEQUENCE_OF.h"
#include "constr_SEQUENCE_OF.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Vanetza_Security_MultiSignedCtl__tbsCtl_PR {
	Vanetza_Security_MultiSignedCtl__tbsCtl_PR_NOTHING,	/* No components present */
	Vanetza_Security_MultiSignedCtl__tbsCtl_PR_FullIeeeTbsCtl
} Vanetza_Security_MultiSignedCtl__tbsCtl_PR;
typedef enum Vanetza_Security_MultiSignedCtl__unsigned_PR {
	Vanetza_Security_MultiSignedCtl__unsigned_PR_NOTHING,	/* No components present */
	Vanetza_Security_MultiSignedCtl__unsigned_PR_SequenceOfCertificate
} Vanetza_Security_MultiSignedCtl__unsigned_PR;

/* Forward declarations */
struct Vanetza_Security_CtlSignatureSpdu;

/* Vanetza_Security_MultiSignedCtl */
typedef struct Vanetza_Security_MultiSignedCtl {
	Vanetza_Security_Ieee1609dot2dot1MsctlType_t	 type;
	struct Vanetza_Security_MultiSignedCtl__tbsCtl {
		Vanetza_Security_MultiSignedCtl__tbsCtl_PR present;
		union Vanetza_Security_MultiSignedCtl__Vanetza_Security_tbsCtl_u {
			Vanetza_Security_FullIeeeTbsCtl_t	 FullIeeeTbsCtl;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} tbsCtl;
	struct Vanetza_Security_MultiSignedCtl__unsigned {
		Vanetza_Security_MultiSignedCtl__unsigned_PR present;
		union Vanetza_Security_MultiSignedCtl__Vanetza_Security_unsigned_u {
			Vanetza_Security_SequenceOfCertificate_t	 SequenceOfCertificate;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} Unsigned;
	struct Vanetza_Security_MultiSignedCtl__signatures {
		A_SEQUENCE_OF(struct Vanetza_Security_CtlSignatureSpdu) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} signatures;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Vanetza_Security_MultiSignedCtl_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Vanetza_Security_MultiSignedCtl;
extern asn_SEQUENCE_specifics_t asn_SPC_Vanetza_Security_MultiSignedCtl_specs_1;
extern asn_TYPE_member_t asn_MBR_Vanetza_Security_MultiSignedCtl_1[4];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "CtlSignatureSpdu.h"

#endif	/* _Vanetza_Security_MultiSignedCtl_H_ */
#include "asn_internal.h"
