/*
 * Generated by asn1c
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "TS102894-2v251-CDD.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -fprefix=Vanetza_ITS2_ -R`
 */

#include "PathPredicted2.h"

asn_TYPE_member_t asn_MBR_Vanetza_ITS2_PathPredicted2_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct Vanetza_ITS2_PathPredicted2, pathPredicted),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Vanetza_ITS2_PathPredicted,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"pathPredicted"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Vanetza_ITS2_PathPredicted2, usageIndication),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Vanetza_ITS2_UsageIndication,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"usageIndication"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Vanetza_ITS2_PathPredicted2, confidenceLevel),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Vanetza_ITS2_ConfidenceLevel,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"confidenceLevel"
		},
};
static const ber_tlv_tag_t asn_DEF_Vanetza_ITS2_PathPredicted2_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_Vanetza_ITS2_PathPredicted2_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* pathPredicted */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* usageIndication */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* confidenceLevel */
};
asn_SEQUENCE_specifics_t asn_SPC_Vanetza_ITS2_PathPredicted2_specs_1 = {
	sizeof(struct Vanetza_ITS2_PathPredicted2),
	offsetof(struct Vanetza_ITS2_PathPredicted2, _asn_ctx),
	asn_MAP_Vanetza_ITS2_PathPredicted2_tag2el_1,
	3,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	3,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_Vanetza_ITS2_PathPredicted2 = {
	"PathPredicted2",
	"PathPredicted2",
	&asn_OP_SEQUENCE,
	asn_DEF_Vanetza_ITS2_PathPredicted2_tags_1,
	sizeof(asn_DEF_Vanetza_ITS2_PathPredicted2_tags_1)
		/sizeof(asn_DEF_Vanetza_ITS2_PathPredicted2_tags_1[0]), /* 1 */
	asn_DEF_Vanetza_ITS2_PathPredicted2_tags_1,	/* Same as above */
	sizeof(asn_DEF_Vanetza_ITS2_PathPredicted2_tags_1)
		/sizeof(asn_DEF_Vanetza_ITS2_PathPredicted2_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_Vanetza_ITS2_PathPredicted2_1,
	3,	/* Elements count */
	&asn_SPC_Vanetza_ITS2_PathPredicted2_specs_1	/* Additional specs */
};

