/*
 * Generated by asn1c
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "TS102894-2v251-CDD.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -fprefix=Vanetza_ITS2_ -R`
 */

#ifndef	_Vanetza_ITS2_RoadDamageClass_H_
#define	_Vanetza_ITS2_RoadDamageClass_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Vanetza_ITS2_RoadDamageClass {
	Vanetza_ITS2_RoadDamageClass_unknown	= 0,
	Vanetza_ITS2_RoadDamageClass_asphalt_pothole	= 1,
	Vanetza_ITS2_RoadDamageClass_asphalt_cracking	= 2,
	Vanetza_ITS2_RoadDamageClass_asphalt_rutting	= 3,
	Vanetza_ITS2_RoadDamageClass_asphalt_ravelling	= 4,
	Vanetza_ITS2_RoadDamageClass_asphalt_corrugation	= 5,
	Vanetza_ITS2_RoadDamageClass_asphalt_edgeBreaks	= 6,
	Vanetza_ITS2_RoadDamageClass_asphalt_depression	= 7,
	Vanetza_ITS2_RoadDamageClass_asphalt_patching	= 8,
	Vanetza_ITS2_RoadDamageClass_asphalt_polishing	= 9,
	Vanetza_ITS2_RoadDamageClass_asphalt_swelling	= 10,
	Vanetza_ITS2_RoadDamageClass_asphalt_bleeding	= 11,
	Vanetza_ITS2_RoadDamageClass_concrete_faulting	= 21,
	Vanetza_ITS2_RoadDamageClass_concrete_jointSpalling	= 22,
	Vanetza_ITS2_RoadDamageClass_concrete_cracking	= 23,
	Vanetza_ITS2_RoadDamageClass_concrete_polishing	= 24,
	Vanetza_ITS2_RoadDamageClass_concrete_punchouts	= 25,
	Vanetza_ITS2_RoadDamageClass_concrete_blowup	= 26,
	Vanetza_ITS2_RoadDamageClass_concrete_patching	= 27,
	Vanetza_ITS2_RoadDamageClass_concrete_delamination	= 28
} e_Vanetza_ITS2_RoadDamageClass;

/* Vanetza_ITS2_RoadDamageClass */
typedef long	 Vanetza_ITS2_RoadDamageClass_t;

/* Implementation */
extern asn_oer_constraints_t asn_OER_type_Vanetza_ITS2_RoadDamageClass_constr_1;
extern asn_per_constraints_t asn_PER_type_Vanetza_ITS2_RoadDamageClass_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_Vanetza_ITS2_RoadDamageClass;
asn_struct_free_f Vanetza_ITS2_RoadDamageClass_free;
asn_struct_print_f Vanetza_ITS2_RoadDamageClass_print;
asn_constr_check_f Vanetza_ITS2_RoadDamageClass_constraint;
ber_type_decoder_f Vanetza_ITS2_RoadDamageClass_decode_ber;
der_type_encoder_f Vanetza_ITS2_RoadDamageClass_encode_der;
xer_type_decoder_f Vanetza_ITS2_RoadDamageClass_decode_xer;
xer_type_encoder_f Vanetza_ITS2_RoadDamageClass_encode_xer;
jer_type_encoder_f Vanetza_ITS2_RoadDamageClass_encode_jer;
oer_type_decoder_f Vanetza_ITS2_RoadDamageClass_decode_oer;
oer_type_encoder_f Vanetza_ITS2_RoadDamageClass_encode_oer;
per_type_decoder_f Vanetza_ITS2_RoadDamageClass_decode_uper;
per_type_encoder_f Vanetza_ITS2_RoadDamageClass_encode_uper;
per_type_decoder_f Vanetza_ITS2_RoadDamageClass_decode_aper;
per_type_encoder_f Vanetza_ITS2_RoadDamageClass_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _Vanetza_ITS2_RoadDamageClass_H_ */
#include "asn_internal.h"
