#!/usr/bin/env python3
"""Deterministic allowlists for the IDF port, including ASN.1 dependency closure.

Run after an upstream merge, then review the generated diff. Unselected ITS
services, RPC, host tools, GNSS drivers, PQC and PKI clients are not compiled.
"""
import hashlib
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
PORT = ROOT / 'ports/esp_idf'


def write_changed(path, text):
    # Avoid forcing an IDF reconfigure when the allowlist is unchanged.
    if not path.exists() or path.read_text() != text:
        path.write_text(text)


def module(name):
    text = (ROOT / 'vanetza' / name / 'CMakeLists.txt').read_text()
    match = re.search(r'set\(CXX_SOURCES\s+(.*?)\)', text, re.S)
    if not match:
        match = re.search(r'add_vanetza_component\(' + name + r'\s+(.*?)\)', text, re.S)
    return [f'vanetza/{name}/{s}' for s in match[1].split() if s.endswith('.cpp')]


def asn_closure(directory, roots):
    base = ROOT / 'vanetza/asn1' / directory
    pending = [base / f'{name}.h' for name in roots]
    seen = set()
    sources = set()
    while pending:
        path = pending.pop()
        if path in seen:
            continue
        seen.add(path)
        source = path.with_suffix('.c')
        if source.is_file():
            sources.add(source.relative_to(ROOT).as_posix())
            pending.append(source)
        for include in re.findall(r'#include\s+"([^"]+)"', path.read_text()):
            dep = path.parent / include
            if dep.is_file() and dep.parent == base:
                pending.append(dep)
    return sorted(sources)


def main():
    groups = {'base': module('access') + module('common') + module('net')}
    # Router still needs both security envelope parsers through its upstream
    # SecuredMessage variant. No dummy signer, crypto factory or PKI is linked.
    security = module('security')
    exclude = ('backend', 'persistence', 'certificate_provider', 'certificate_validator',
               'sign_service', 'sign_header_policy', 'verify_service', 'verification',
               'trust_store', 'hmac', 'sha.cpp', 'delegating_security_entity',
               'certificate_cache', 'revocation_lookup', 'issuer_memory_lookup',
               'location_checker', 'distance.cpp', 'geometry.cpp', 'hash.cpp',
               'peer_request_tracker', 'cam_ssp', 'issuer_memory')
    security = [p for p in security if not any(x in p for x in exclude)]
    groups['network'] = module('geonet') + module('btp') + module('dcc') + security + [
        'vanetza/geodesy/geodesy.cpp', 'vanetza/geodesy/haversine.cpp',
        'vanetza/security/v3/distance.cpp', 'vanetza/security/v3/geometry.cpp',
        'vanetza/security/v3/boost_geometry.cpp']
    groups['asn_support'] = ['vanetza/asn1/' + s for s in
                            (ROOT / 'vanetza/asn1/asn1c_support_sources.txt').read_text().splitlines()
                            if s and not s.startswith('#')]
    groups['asn_support'] += ['vanetza/asn1/memory.c', 'vanetza/asn1/asn1c_wrapper.cpp',
                              'vanetza/asn1/type_traits.cpp']
    groups['security_asn'] = asn_closure('security', ['EtsiTs103097Data', 'Certificate', 'EtsiTs103097Certificate'])
    for service in ('cam', 'denm', 'vam'):
        groups[service] = asn_closure('its/r2', [service.upper()])
    cmake = '# Generated by tools/source_manifest.py. Review changes after upstream updates.\n'
    for name, paths in groups.items():
        cmake += f'set(VIDF_{name.upper()}_SOURCES\n'
        cmake += ''.join(f'    "${{VIDF_ROOT}}/{p}"\n' for p in sorted(set(paths)))
        cmake += ')\n'
    write_changed(PORT / 'sources.cmake', cmake)
    manifest = {'upstream': 'https://github.com/riebl/vanetza',
                'commit': 'a7cacc1879f3e2124dfb8ef2d83886b1e82d3b36',
                'license': 'LGPL-3.0-or-later; see LICENSE.md and per-file notices',
                'groups': {k: sorted(set(v)) for k, v in groups.items()},
                'sha256': {p: hashlib.sha256((ROOT / p).read_bytes()).hexdigest()
                           for p in sorted({p for v in groups.values() for p in v})}}
    write_changed(PORT / 'source-manifest.json', json.dumps(manifest, indent=2) + '\n')
    print({name: len(paths) for name, paths in groups.items()})


if __name__ == '__main__':
    main()
